[project]
name = "todo-backend"
version = "0.1.0"
description = "Backend for the todo application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.9.10",
    "pytest>=8.3.3",
    "httpx>=0.27.2",
] 